### ISSUE TITLE
How to exchange packets between two clients?

### ISSUE THREAD

**Issue by Leeo97one** [PvdBerg1998/PNet#6]
Hi,

I have created one server and two clients.

Server:
```java
server = new PlainServer();
server.setListener(new ServerListener());
server.start(10240);
```
Client 1:
```java
client1 = new PlainClient();
client1.setClientListener(new ClientListener());
client1.connect("localhost", 10240);
```
Client 2:
```java
client2 = new PlainClient();
client2.setClientListener(new ClientListener());
client2.connect("localhost", 10240);
```
I can send a packet from Client 1 to the Server with:
```java
packet1 = new PacketBuilder(Packet.PacketType.Request).withInt(10).withString("test").withBoolean(true).build();
client1.send(packet1);
```
But I'm not sure on how send this packet to Client 2? :thinking:
(`ServerListener()` and `ClientListener()` are both an implementation of `PNetListener`)

**Comment by PvdBerg1998** [comment]
You can't. PNet is meant for client <=> server communication and not P2P. If you want something like this, the server should forward the packet to the other client.

**Comment by Leeo97one** [comment]
It's exactly what I want to do, but I don't know how to perform this forwarding :-/

**Comment by PvdBerg1998** [comment]
I don't know your use case but you could choose to forward all packets sent by any client to all the other clients.

**Comment by Leeo97one** [comment]
Sorry, perhaps I'm dumb but I really don't see how the server can send packet to client x)
I guess I have to write some code in the server listener, but what? (Or perhaps I'm completely wrong...)
```java
public void onReceive(Packet packet, Client client) throws IOException {
    // What to write here?
}
```

**Comment by frankvdberg** [comment]
You will need to write a peer to peer protocol on top of pnet.
