### ISSUE TITLE
Maximum number of simultaneous connections

### ISSUE THREAD

**Issue by wlkjlc** [PvdBerg1998/PNet#7]
I like the PNet API design.
I saw this.
https://github.com/PvdBerg1998/PNet/blob/master/src/test/java/nl/pvdberg/pnet/BenchmarkTest.java
It is only tested on 1 client 1 server.
Multi client 1 server has not been tested.
In the case of multiple clients, depending on the implementation, a large number of threads are created, or if some communication is delayed, the whole is delayed.
How much performance do you get?

**Comment by wlkjlc** [comment]
I wrote many clients many servers random connection time test. the result is bad.
I insert this random wait code to AutoClient.java
    @Override
    public boolean connect(final String host, final int port)
    {
    	//for benchmark test
    	try {
			Thread.sleep(new Random().nextInt(5000));
		} catch (InterruptedException e) {
		}

I use this client setup.
			Client client = new AsyncClient(
					new AutoClient(new PlainClient(), "localhost", port));

the result is too slow. it means a client connection blocks other clients.

**Comment by wlkjlc** [comment]
I insert this code to ClientImpl.java. but same bad result.
        try
        {
            setSocket(sf.getSocket(host, port));
        	//for benchmark test
        	try {
    			Thread.sleep(new Random().nextInt(5000));
    		} catch (InterruptedException e) {
    		}

            logger.debug("Connected");
            return true;
        }

**Comment by PvdBerg1998** [comment]
Sorry for the late response, this library is unmaintained. It probably depends on the system you are running it on, I'd say give it a try and judge for yourself if it's fast enough!
